### GENERAL SETTINGS ###

# Site settings
title: TINKTANK
description: "TinkTank est un accélérateur de projets collaboratifs culturels."
analytics: UA-8754239-13 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://tinktank.club"

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#C7C7C7" 
  primary_rgb: "189,195,199" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#662D91" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/groups/1459614080942550/
  - title: twitter
    url: http://twitter.com/tinktankMTL

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 7255 Alexandra, suite 203
    - H2R 2Y9, Montréal,
    - QC, Canada.
email: ping@tinktank.club
tel: +438 398 5784


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Arthur Schmitt 
    position: Lead prototypage
    text: "Ingénieur (ENSAM, Imperial College) et designer (RCA), Arthur est passionné par les nouvelles technologies et les pratiques collaboratives. Installé depuis un an à Montréal, il a auparavant participé à l’émergence des fablabs en France, notamment en contribuant à l'ouverture du premier fablab dans le centre de Paris."
    img: arthur_carre.jpg
    social:
      - title: envelope #use for email address
        url: mailto:arthur@tinktank.org
      - title: twitter
        url: http://twitter.com/tart2000
  - name: Justine G. Chapleau
    position: Lead projets
    text: "Graduée de la maîtrise en Muséologie à l’UdeM et à l’UQÀM où elle s’est spécialisée dans la reconnaissance et le recensement des initiatives de hacking culturel en milieu muséal, Justine tente toujours de repousser les limites préétablies en réalisant des projets multidisciplinaires."
    img: justine_carre.jpg
    social:
      - title: envelope #use for email address
        url: mailto:justine@tinktank.org
      - title: twitter
        url: http://twitter.com/justineGChaplea
  - name: Lucie Brillouet 
    position: Lead design 
    text: "Diplômée en design industriel (BDI / UdeM) et graduée du DESS in Communication Studies (Concordia), sa soif de culture ne s’arrête pas là. Après avoir mis un pied dans l’organisation d’événement culturel grâce au festival Art Souterrain, Lucie souhaite accompagner l’émergence de nouvelles pratiques collaboratives au croisement de la culture, du design et des nouvelles technologies."
    img: lucie_carre.jpg
    social:
      - title: envelope #use for email address
        url: mailto:lucie@tinktank.org
      - title: twitter
        url: http://twitter.com/Lucie_Brllt

    
# Clients information. Shown on Home and About pages.
clients:
  - name: Banff Center
    img: banff.png
    link: http://www.banffcentre.ca/
  - name: MBAM
    img: mbam.png
    link: http://www.mbam.qc.ca/
  - name: Espaces Temps 
    img: espacestemps.png 
    link: http://espacestemps.ca/ 
    
# Principes de travail 
principes:
  - name: Prototypage
    faicon: cubes
    texte: "Le prototype est au coeur de notre philosophie de travail et de nos projets. Il permet de tester rapidement des idées et de réunir une équipe autour d'un concept."
  - name: Collaboration 
    faicon: comments
    texte: "Notre passion : faire travailler les gens de manière collaborative. Pour cela, nous expérimentons en permanence avec les nouvelles pratiques et les nouveaux outils."
  - name: Ouverture
    faicon: unlock
    texte: "Nous pensons qu'à l'heure du numérique, l'innovation doit passer par l'ouverture et le partage. C'est pourquoi tous les projets que nous développons sont documentés et partagés."

# Questions 
questions: 
  - titre: "J'ai une idée de projet, est-ce que je peux vous en parler ?"
    reponse: "Oui !"
    n: 1
  - titre: "Travaillez-vous avec des entreprises ?"
    reponse: "Nous travaillons avec toutes les personnes / institutions / organisations qui portent les mêmes valeurs que nous, sans restrictions. Si c'est votre cas, n'hésitez pas à nous contacter pour en discuter."
    n: 2

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "TinkTank est un accélérateur de projets collaboratifs culturels."
about_plus: "A mi-chemin entre un fablab, un living lab et un incubateur, TinkTank accompagne l'émergence d'une nouvelle génération de projets technologiques culturels, basés sur le commun."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
